---
- hosts: webservers
  gather_facts: yes
  become: yes
  tasks:
    - name: nginx latest installed
    become: yes
    apt:
      name: nginx
      state: latest
    - name: php7.4-fpm
      apt:
        name: php7.4-fpm
        state: present