---
- hosts: webservers
  gather_facts: yes
  tasks:
   - name: Update apt cache
     become: yes
     apt:
      update_cache: yes
   - name: nginx install
     become: yes
     apt:
      name: nginx
      state: latest
   - name: php-fpm install
     become: yes
     apt:
      name: php7.4-fpm
      state: present
   - name: Starting nginx
     become: yes
     service:
         name: nginx
         state: started
   - name: Copying php file
     become: yes
     copy:
       src: templates/index.php
       dest: /var/www/html/
   - name: Add template file
     become: yes
     template:
       src: templates/nginx.conf
       dest: /etc/nginx/sites-available/default
   - name: Enabling conf files in nginx available sites
     become: yes
     file:
       src: /etc/nginx/sites-available/default
       dest: /etc/nginx/sites-enabled/default
       state: link
   - name: Restart Web Servers
     become: yes
     service:
          name: nginx
          state: restarted

- hosts: haproxy
  gather_facts: yes
  vars:
    haproxy_mode: http
    haproxy_algorithm: roundrobin
    haproxy_backend: Web_servers
  become: yes
  tasks:
   - name: update apt cache in Haproxy
     apt:
      update_cache: yes
   - name: Install haproxy
     become: yes
     apt:
      name: haproxy
      state: present
   - name: update HAProxy config file
     template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
   - name: Restart HAProxy
     service:
       name: haproxy
       state: restarted

